### ISSUE TITLE
Can't run example of project

### ISSUE THREAD

**Issue by mrssource** [trailofbits/rattle#19]
I ran this command to test this tool at beginning
`python3 rattle-cli.py --input inputs/kingofether/KingOfTheEtherThrone.bin -0`

But got following error:
```
File "rattle-cli.py", line 46
    logger.info(f"Rattle running on input: {args.input.name}")
                                                            ^
SyntaxError: invalid syntax
```

**Comment by disconnect3d** [comment]
Hey, thanks for the issue!

This is because we use [Literal String Interpolation (see pep-498)](https://www.python.org/dev/peps/pep-0498/) that was introduced in Python 3.6. That being said `rattle` needs to be run with Python >= 3.6.

You can use [pyenv](https://github.com/pyenv/pyenv) to manage multiple versions of Python on your system (it also works fine with [virtualenv](https://virtualenv.pypa.io/en/stable/)).

We will add this info to README soon.

**Comment by disconnect3d** [comment]
@mrssource  Hmm, it is weird that your Python didn't die on this assertion:
https://github.com/trailofbits/rattle/blob/c9b016ee61e465fdc94cb9924fd07b385d8521da/rattle-cli.py#L15

Can you show what does it print:
```bash
python3 -c "import sys; print(sys.version_info)"
```

**Comment by mrssource** [comment]
> Can you show what does it print:
> 
> ```shell
> python3 -c "import sys; print(sys.version_info)"
> ```

Here is my output
```
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by disconnect3d** [comment]
Idk why it happens. If you want to help looking up why is that happening, let us know if you find sth.

**Comment by withzombies** [comment]
> > Can you show what does it print:
> > ```shell
> > python3 -c "import sys; print(sys.version_info)"
> > ```
> 
> It seems weird to me also. Here is my output
> 
> ```
> sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
> ```

You should update your python version to 3.6 or later. I personally am running 3.7:

```
$ python3 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by mrssource** [comment]
> Idk why it happens. If you want to help looking up why is that happening, let us know if you find sth.

A code written in Python gets parsed, analyzed, and fed into an interpreter respectively. Hence, the complier begins with a parser which raises a syntax error (due to incompatible version) first. Your assertion was still not reached in step.

**Comment by mrssource** [comment]
A code written in Python gets parsed, analyzed, and fed into an interpreter sequentially. Hence, the complier begins with a parser which raises a syntax error (due to incompatible version) first. Your assertion was still not reached in step.

**Comment by disconnect3d** [comment]
@mrssource Oh right, that makes sense. Thanks :).
